language: node_js
branches:
  - development
  - master
node_js:
  - 12
  - 11
  - 10
  - 8
env:
  - SEQUELIZE_VERSION=5.6
  - SEQUELIZE_VERSION=5.7
matrix:
  fast_finish: true
  include:
    - env: SEQUELIZE_VERSION=5.1
    - env: SEQUELIZE_VERSION=5.2
    - env: SEQUELIZE_VERSION=5.3
    - env: SEQUELIZE_VERSION=5.4
    - env: SEQUELIZE_VERSION=5.5

cache:
  directories:
    - $HOME/.npm

services: postgresql

before_script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run audit-ci --moderate && npm outdated; fi
  - npm install sequelize@$SEQUELIZE_VERSION
script:
  - npm run lint
  - npm test
  - codecov -f coverage/*.json
