language: node_js
matrix:
  - node_js: 8
    env: SEQUELIZE_VERSION=5.6
  - node_js: 8
    env: SEQUELIZE_VERSION=5.7
  - node_js: 10
    env: SEQUELIZE_VERSION=5.6
  - node_js: 10
    env: SEQUELIZE_VERSION=5.7
  - node_js: 11
    env: SEQUELIZE_VERSION=5.6
  - node_js: 11
    env: SEQUELIZE_VERSION=5.7
  - node_js: 12
    env: SEQUELIZE_VERSION=5.2
  - node_js: 12
    env: SEQUELIZE_VERSION=5.4
  - node_js: 12
    env: SEQUELIZE_VERSION=5.6
  - node_js: 12
    env: SEQUELIZE_VERSION=5.7

cache:
  directories:
    - $HOME/.npm

services: postgresql

before_script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run audit-ci --moderate && npm outdated; fi
  - npm install sequelize@$SEQUELIZE_VERSION
script:
  - npm run lint
  - npm test
  - codecov -f coverage/*.json
